"use client";
import { useEffect,useRef,useState } from "react";
import styles from "./scanner-page-editor.module.css";

export function ScannerPageEditor({image,onSave,onClose}:{image:Blob;onSave:(blob:Blob)=>void;onClose:()=>void}){
 const element=useRef<HTMLCanvasElement>(null),fabricCanvas=useRef<import("fabric").Canvas|null>(null),history=useRef<string[]>([]),cursor=useRef(-1);const[color,setColor]=useState("#ef4444"),[width,setWidth]=useState(4);
 useEffect(()=>{let disposed=false;void(async()=>{const {Canvas,FabricImage}=await import("fabric");if(disposed||!element.current)return;const dimensions=await createImageBitmap(image),scale=Math.min(1,900/dimensions.width,650/dimensions.height),canvasWidth=Math.round(dimensions.width*scale),canvasHeight=Math.round(dimensions.height*scale);dimensions.close();const canvas=new Canvas(element.current,{width:canvasWidth,height:canvasHeight,backgroundColor:"white"});fabricCanvas.current=canvas;const url=URL.createObjectURL(image);const picture=await FabricImage.fromURL(url);URL.revokeObjectURL(url);picture.set({left:0,top:0,selectable:false,evented:false,scaleX:canvas.width/picture.width!,scaleY:canvas.height/picture.height!});canvas.add(picture);canvas.sendObjectToBack(picture);const snapshot=()=>{const value=JSON.stringify(canvas.toJSON());if(history.current[cursor.current]===value)return;history.current=history.current.slice(0,cursor.current+1);history.current.push(value);cursor.current=history.current.length-1};snapshot();canvas.on("object:added",snapshot);canvas.on("object:modified",snapshot);canvas.on("path:created",snapshot)})();return()=>{disposed=true;fabricCanvas.current?.dispose();fabricCanvas.current=null}},[image]);
 const drawing=async(erase=false)=>{const canvas=fabricCanvas.current;if(!canvas)return;const{PencilBrush}=await import("fabric");canvas.isDrawingMode=true;const brush=new PencilBrush(canvas);brush.color=erase?"#ffffff":color;brush.width=width;canvas.freeDrawingBrush=brush};
 const select=()=>{if(fabricCanvas.current)fabricCanvas.current.isDrawingMode=false};
 const text=async()=>{const canvas=fabricCanvas.current;if(!canvas)return;select();const{IText}=await import("fabric");const object=new IText("Текст",{left:40,top:40,fill:color,fontSize:28});canvas.add(object);canvas.setActiveObject(object)};
 const blur=async()=>{const canvas=fabricCanvas.current;if(!canvas)return;select();const{Rect}=await import("fabric");canvas.add(new Rect({left:50,top:50,width:180,height:80,fill:"rgba(100,116,139,.88)",stroke:"#64748b",strokeDashArray:[5,4]}))};
 const restore=async(index:number)=>{const canvas=fabricCanvas.current;if(!canvas||index<0||index>=history.current.length)return;cursor.current=index;await canvas.loadFromJSON(history.current[index]);canvas.requestRenderAll()};
 const save=()=>{const canvas=fabricCanvas.current;if(!canvas)return;select();const regions=canvas.getObjects().filter(object=>object.type==="rect"&&object.fill==="rgba(100,116,139,.88)");regions.forEach(object=>object.set({visible:false}));canvas.requestRenderAll();const source=canvas.getElement(),output=document.createElement("canvas");output.width=source.width;output.height=source.height;const context=output.getContext("2d")!;context.drawImage(source,0,0);const ratioX=source.width/canvas.width,ratioY=source.height/canvas.height;for(const object of regions){const left=object.left*ratioX,top=object.top*ratioY,width=object.getScaledWidth()*ratioX,height=object.getScaledHeight()*ratioY;context.save();context.filter="blur(12px)";context.drawImage(source,left,top,width,height,left,top,width,height);context.restore()}regions.forEach(object=>object.set({visible:true}));canvas.requestRenderAll();output.toBlob(blob=>{if(blob)onSave(blob)},"image/jpeg",.9)};
 return <div className={styles.editor}><div className={styles.editorToolbar}><button onClick={select}>Выбор</button><button onClick={()=>void drawing()}>Перо</button><button onClick={()=>void drawing(true)}>Ластик</button><button onClick={()=>void text()}>Текст</button><button onClick={()=>void blur()}>Размытие</button><button onClick={()=>void drawing()}>Подпись</button><input type="color" value={color} onChange={event=>setColor(event.target.value)}/><input aria-label="Толщина" type="range" min={1} max={20} value={width} onChange={event=>setWidth(Number(event.target.value))}/><button onClick={()=>void restore(cursor.current-1)}>Отменить</button><button onClick={()=>void restore(cursor.current+1)}>Вернуть</button></div><div className={styles.editorCanvas}><canvas ref={element}/></div><footer><button onClick={onClose}>Отмена</button><button className={styles.primary} onClick={save}>Применить</button></footer></div>
}
